version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt -t package/
  build:
    commands:
      - cp lambda_function.py package/
      - cp process_logs.py package/
      - cd package && zip -r ../lambda-package.zip .
artifacts:
  files:
    - lambda-package.zip

