version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt -t package/  # Install dependencies inside package folder
  build:
    commands:
      - cp lambda_function.py package/
      - cp process_logs.py package/
      - cd package && zip -r ../lambda-package.zip .  # ZIP EVERYTHING INSIDE package/
      - cd .. && zip -r lambda-package.zip package/  # 🔥 ADD package/ ITSELF
  post_build:
artifacts:
  files:
    - lambda-package.zip

